#!/usr/bin/env node
var SCRAPE_QUEUE = 'jobs.scrape';

var logger = require('logfmt');
var WorkQueueBroker = require('node-redis-queue').WorkQueueBroker;

var broker = new WorkQueueBroker();
broker.connect(function() {
  logger.log({type: 'info', msg: 'connected', service: 'node-redis-queue'});
  var scrapeQueue = broker.createQueue(SCRAPE_QUEUE);
  scrapeQueue.consume(function(job, ack) {
    logger.log({type: 'info', msg: 'consuming', data: JSON.stringify(job)});
    ack();
  });
});


