#!/usr/bin/env node
var SCRAPE_QUEUE = 'jobs.scrape';

var logger = require('logfmt');
var WorkQueueBroker = require('node-redis-queue').WorkQueueBroker;
var jobs = [
  {id: 1, url: 'http://www.bbc.com/news/health-29707393', userId: 123},
  {id: 2, url: 'http://www.cdc.gov/vhf/ebola/outbreaks/2014-west-africa/index.html', userId: 123}
];

var broker = new WorkQueueBroker();
broker.connect(function() {
  logger.log({type: 'info', msg: 'connected', service: 'qput'});
  var scrapeQueue = broker.createQueue(SCRAPE_QUEUE);
  for(i=0; i < jobs.length; i++) {
    logger.log({type: 'info', msg: 'consuming', data: JSON.stringify(jobs[i])});
    scrapeQueue.send(jobs[i]);
  }
  broker.end();
  logger.log({type: 'info', msg: 'done', service: 'qput'});
});


